config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  resources :posts do
    resources :comments
  end

  resources :attachments, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, touch: true
  belongs_to :author, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  belongs_to :author, class_name: 'User'

  has_many_attached :images, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, class_name: 'Post', foreign_key: :author_id
  has_many :comments, class_name: 'Comment', foreign_key: :author_id

  def author?(resource)
    resource.author_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!, only: :destroy

  def destroy
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge if current_user.author?(@image.record)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_post, only: %i[create destroy]

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(author_id: current_user.id)
  end

  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_post, only: %i[show edit update destroy]

  def index
    author_id = params[:author_id]
    if author_id
      @posts = Post.where('author_id = ?', author_id).order('updated_at desc').page params[:page]
    else
      @posts = Post.all.order('updated_at desc').page params[:page]
    end
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def update
    if current_user.author?(@post)
      @post.update(post_params)
      redirect_to @post
    else
      redirect_to @post, alert: 'You is not author post'
    end
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Your post successfully created'
    else
      render :new
    end
  end

  def destroy
    if current_user.author?(@post)
      @post.destroy
      redirect_to root_path, notice: 'Your post successfully delete'
    else
      redirect_to @post, alert: 'You is not author post'
    end
  end

  private

  def load_post
    @post = Post.with_attached_images.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :author_id, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'warning', 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end

  def flash_message
    tag.div id: 'flash-message' do
      render 'shared/flash'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/nav' %>
  <%= render 'shared/flash' %>
  <%= yield %>
  </body>
</html>

app/views/posts/_post.html.slim
.container-fluid.col-md-7.mb-3
  .row.border-bottom
    h2= link_to post.title, post
    p= post.body

app/views/posts/edit.html.slim
.edit-post
  .container-fluid.col-md-7
    = form_with model: @post do |f|
      p
        p= f.label :title, 'Your post'
        = f.text_field :title, class: 'form-control mt-2'

      p
        p= f.label :body
        = f.text_area :body, class: 'form-control mt-2'

      p
        = f.label :images, class: 'formFileSm'
        = f.file_field :images, multiple: true, direct_upload: true, class: 'form-control form-control-sm'

      p= f.submit 'Save', class: 'btn btn-sm btn-success'

app/views/posts/index.html.slim
.container-fluid.d-flex.justify-content-center
  -if current_user
    = link_to 'Все', posts_path, class: 'btn-sm page-link me-1'
    = link_to 'Свои', posts_path(author_id: current_user.id), class: 'btn-sm page-link'

= render @posts
= paginate @posts, theme: 'bootstrap-5', pagination_class: 'pagination-sm p-4 flex-wrap justify-content-center'

app/views/posts/new.html.slim
= render 'shared/errors', resource: @post

= form_with model: @post, data: { turbo: false } do |f|
  p
    p= f.label :title, 'Your post'
    = f.text_field :title

  p
    p= f.label :body
    = f.text_area :body

  p
    = f.label :images, 'Image'
    = f.file_field :images, multiple: true

  p= f.submit 'Create post'

app/views/posts/show.html.slim
.post-errors
  = render 'shared/errors', resource: @post

.post
  = render @post
  - if @post.images.attached?
    .container-fluid.col-md-7
      - @post.images.each do |image|
        = link_to image.filename.to_s, url_for(image)
        p= link_to 'Delete image', attachment_path(image.id), data: { 'turbo-method': :delete }, class: 'btn btn-sm btn-danger', method: :delete

.container-fluid.col-md-7.border-bottom
  .btn-group
    p= link_to 'Delete post', @post, method: :delete, data: { 'turbo-method': :delete }, class: 'btn btn-sm btn-danger me-1'
    p= link_to 'Edit post', edit_post_path(@post), class: 'btn btn-sm btn-secondary', form: 'edit_form'

.comments
  .container-fluid.col-md-7.mt-3
    | Comments
    - @post.comments.each do |comment|
      p
        strong= comment.author.email
        |: &nbsp;
        = comment.body

    = form_with model: [@post, @post.comments.build], data: { turbo: false } do |f|
      = f.text_area :body, class: 'form-control mt-2'
      = f.submit 'Add comment', class: 'btn btn-sm btn-success mt-2'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.erb
<div class="flash-container col-md-9 mx-auto">
  <% flash.each do |type, msg| %>
    <%= content_tag :div, class: "alert #{ bootstrap_class_for_flash(type) } alert-dismissable fade show", role: "alert" do %>
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
        <use xlink:href="#info-fill" />
      </svg>
      <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= msg %>
    <% end %>
  <% end %>
</div>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" /> </symbol>
</svg>

app/views/shared/_nav.html.slim
nav class="navbar sticky-top" style="background-color: #f0f0f0"
  .container-fluid
    .brand
      = link_to 'Blog', root_path, class: 'btn btn-secondary'
    .right
      - if user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-secondary'
      - else
        = link_to 'Login', new_user_session_path, class: 'btn btn-success'
        = link_to 'Signup', new_user_registration_path, class: 'btn'

    .left
      = link_to 'New post', new_post_path, class: 'btn btn-success'